
exports.words = ['sokeria', 'toiminta', 'monimutkainen', 'huvittaa', 'tunnistaa', 
							'maailma', 'unelias', 'sähikäinen', 'kovaa', 'kiiltävä', 'harrastus', 
							'vino', 'tuho', 'määräajoin', 'palapeli', 'kognitiivinen', 'paine', 
							'hallita', 'kaula', 'mysteeri', 'piirtää', 'poikamies', 'ghoul', 
							'rutikuiva', 'ilo', 'avioero', 'kodittomia', 'tehokas', 'kuvaileva', 
							'käärmeet', 'rautatie', 'sinertävä', 'valpas', 'jakaa', 'runsas', 'nenäkäs', 
							'harppuuna', 'lukko', 'taitolento', 'häiriintynyt', 'ikäinen', 'oikeuksia', 'neiti', 
							'eleellinen', 'eroottinen', 'kirjallisuus', 'tukkukauppa', 'suppilo', 'tilaisuus', 
							'osasto', 'reipas', 'itse', 'asiassa', 'palkkio', 'ankka', 'puuma', 'nyrkkitappelu', 
							'vahingossa', 'mutteri', 'saatavissa', 'seksuaalinen', 'perehtynyt', 'lade', 
							'pistooli', 'virne', 'huoneisto', 'virtsarakko', 'mellakka', 'ylittää', 'kaada', 
							'lasi', 'syyttää', 'askel', 'ehdotus', 'fantomi', 'aito', 'jako', 'maanjäristys', 
							'lumisade', 'salaisuus', 'jumalaton', 'luottavainen', 'krusifiksi', 'ankkoja', 
							'helistin', 'hätävara', 'kehtolaulu', 'jakelu', 'järjetön', 'negatiivinen', 'ulkomuoto', 
							'pohdintaa', 'suurin', 'kaava', 'kömpelö', 'laatikko', 'konsepti', 'rohkea', 'voitto', 
							'profeetallinen', 'työntövoima', 'omistautua', 'ihannoida', 'paistettu', 'lähde', 'pois', 
							'ennustaa', 'lapanen', 'putoaa', 'kutiava', 'luopua', 'virheenkorjaus', 'leijua', 'gadget', 
							'kiinteä', 'vinyyli', 'kellari', 'rosvo', 'tehtävä', 'vaitelias', 'kikka', 'epäkäytännöllinen', 
							'huono', 'murtuma', 'taistelu', 'kurja', 'maaseutu', 'edustaja', 'korrelaatio', 'liberaali', 'löytää', 
							'neuvonantaja', 'tukehtuminen', 'äiti', 'äänetön', 'kapteeni', 'sanansaattaja', 'rohkeutta', 'majava', 
							'hintelä', 'täplikäs', 'tahra', 'ääretön', 'tehdä', 'yhteistyötä', 'huumaava', 'rapuja', 'tietoinen', 
							'rikosmaailma', 'haara', 'syöminen', 'grandioosi', 'naamio', 'pyhimys', 'valmis', 'pommikone', 'ikävä', 
							'epävarma', 'hyväntahtoinen', 'maali', 'unelmoija', 'swot', 'järjestellä', 'kaivertaa', 'ominaisvektori', 
							'ranne', 'veistoksellinen', 'bogeyman', 'sama', 'kolahtaa', 'lähellä', 'puhdas', 'mutantti', 'viettää', 
							'loistava', 'piiri', 'olla', 'peräisin', 'viitata', 'mateleva', 'keskuudessa', 'kelloja', 'teollinen', 
							'alhaalla', 'tuottaa', 'terveys', 'tömähdys', 'erillinen', 'tunnusta', 'luu', 'parranajo', 'väkijoukko', 
							'sinkauttaa', 'berserk', 'yleinen', 'toiminta', 'harjoitella', 'biologia', 'akustiikka', 'kuplia', 'ghetto', 
							'hallinto', 'kannustaa', 'loukkaus', 'naapuruus', 'kainalosauva', 'rakkaus', 'etuoikeus', 'kaukana', 'sieni', 
							'tarkka', 'jalat', 'ilmapallo', 'sileä', 'epäkohtelias', 'onnekas', 'hurrata', 'puu', 'käärmeihminen', 
							'leija', 'haudattu', 'saapas', 'sekaisin', 'ydin', 'kokoushuone', 'hämmentynyt', 'sukupolvi', 'rakentaa', 
							'pingviini', 'ilkeä', 'ukkonen', 'liikkumaton', 'tehosekoitin', 'onni', 'järvi', 'kunniamerkki', 'löysä', 
							'turvallisuus', 'laskea', 'moninkertaistua', 'harvinainen', 'kolera', 'kirkas', 'mustuus', 'kantaa', 
							'banaanit', 'vaikutelma', 'astronautti', 'punnita', 'häiritä', 'huutaja', 'voitettu', 'suojella', 'päätös', 
							'korvaus', 'happo', 'brändi', 'nyrkki', 'ilkeä', 'laskenta', 'apaattinen', 'signaali', 'kuljetus', 'julma', 
							'grilli', 'laaja', 'huijari', 'eläin', 'häikäistä', 'wiry', 'hukkua', 'raskas', 'poistaa', 'amebamainen', 
							'käsityöläinen', 'ovela', 'vaihtokauppa', 'kansallinen', 'kirahvi', 'kymmeniä', 'hopea', 'vastaus', 
							'jakoavain', 'vastaanotto', 'kymmeneltä', 'asetus', 'kilpailu', 'kritiikki', 'design', 'pakonomainen', 
							'teurastamo', 'pehmoinen', 'taisteleva', 'ärsyttävä', 'pyydä', 'vaistomainen', 'vanki', 'julmuus', 'chide', 
							'likainen', 'keskustassa', 'kuolla', 'orpokoti', 'vedessä', 'katastrofi', 'sivu', 'seremoniallinen', 'tarpeen', 
							'kutsumus', 'ambivalentti', 'leikkikenttä', 'taloudellinen', 'väärinkäyttö', 'kansakunta', 'ystävällisesti', 
							'juoni', 'vihaa', 'mutkattomasti', 'rakastava', 'jälkimaku', 'kuraattori', 'nuoli', 'helmeilevä', 'seksikkäin', 
							'kuormaauto', 'säälittävä', 'himo', 'nopein', 'matkustaa', 'raukea', 'repaleinen', 'kieltää', 'tilaa', 'suosittu', 
							'isä', 'haukka', 'noudattaa', 'kohdata', 'ikävä', 'oksa', 'näkymä', 'yksinäinen', 'ällöttävä', 'paras', 
							'mahdollinen', 'murha', 'varvas', 'tytöt', 'laskettaessa', 'asua', 'atomi', 'parittaja', 'päivä', 'hiljaa', 
							'ilmestyy', 'synkkä', 'valita', 'kypsä', 'terävä', 'upota', 'koetin', 'hämmästyttää', 'röyhkeä', 'tuijottaa', 
							'reitti', 'voimaton', 'jalkapallo', 'kappaletta', 'pieni', 'vanki', 'profeetat', 'pakana', 'viholliset', 
							'sopimus', 'sarana', 'syrjässä', 'nihkeä', 'röyhkeä', 'rangaistus', 'oksentaa', 'peruna', 'lihansyöjä', 
							'merkitys', 'vastuu', 'murskaamalla', 'iguana', 'taaksepäin', 'piirit', 'maku', 'puuttuu', 'muodonmuuttaja', 
							'tulivuoren', 'ryhmittymä', 'vapisevat', 'seuraamus', 'jännittynyt', 'hämmästyttävää', 'saastuminen', 
							'eitoivottuja', 'kana', 'ohjausta', 'takana', 'solmio', 'noita', 'sairas', 'salaus', 'jännitystä', 'ohjain', 
							'magenta', 'sydänsairaita', 'kuoleman', 'hämähäkit', 'tärkeä', 'raaka', 'apina', 'hansikkaat', 'harhaluuloinen', 
							'rajaton', 'lauma', 'rumpu', 'nauttia', 'turvallinen', 'periä', 'riippuva', 'retorinen', 'todistaa', 'jalat', 
							'sato', 'johtaja', 'edessä', 'vaikeus', 'sokeus', 'viettelijä', 'kyljykset', 'seinä', 'lämpöhalvaus', 'syvennys', 
							'salaperäinen', 'aseettomana', 'helmi', 'rupi', 'häikäisevä', 'norsuja', 'kallisarvoinen', 'lintu', 'nopea', 
							'estää', 'nipistää', 'orangutang', 'loputon', 'kestää', 'ihana', 'arvoton', 'harplike', 'puskutraktori', 
							'itäinen', 'suuret', 'silmät', 'koteloida', 'penniäkään', 'rikas', 'geometria', 'talvi', 'sairaanhoitaja', 
							'kynsiä', 'valtava', 'seitsemän', 'isku', 'tarpeeton', 'hyökkääjä', 'rauhoittaa', 'letku', 'ajateltavissa', 
							'taktinen', 'täyttää', 'sato', 'arkku', 'potilas', 'kirjoittaminen', 'merkittävä', 'kolkko', 'merkittävä', 
							'eroottinen', 'uteliaisuudet', 'valita', 'piki', 'kukkulat', 'tilaus', 'uudelleen', 'kiljua', 'kissanpentu', 
							'haukkua', 'norsu', 'mennyt', 'lahja', 'jalka', 'hauras', 'tyylikäs', 'avoinna', 'saippuoida', 'rubiini', 
							'vaeltava', 'alkuun', 'purkaus', 'todella', 'tukeva', 'kerjäläinen', 'teljetä', 'jhk', 'julma', 'pakko', 
							'kaatua', 'määritelmä', 'yhdistelmä', 'selviytyä', 'arkipäiväinen', 'päivittäin', 'pilkkominen', 'kirkkaasti', 
							'matkustaja', 'niukka', 'presidentti', 'stimuloida', 'miellyttävä', 'liitto', 'vetäytyä', 'laskin', 'keskittyä', 
							'lentää', 'kuollut', 'hakata', 'palkinto', 'innostusta', 'bazooka', 'ystävä', 'pelko', 'herttua', 'krapula', 
							'paju', 'hapsut', 'pito', 'puhelu', 'soopeli', 'kruunu', 'asuntovaunu', 'putiikki', 'nostin', 'unelmoida', 
							'kaksitaso', 'selleri', 'vuori', 'kamala', 'kosto', 'kaikki', 'yhteensä', 'luonto', 'kiillottaa', 'satamaan', 
							'soittokello', 'riemuissaan', 'juosta', 'saalistaja', 'helvetin', 'tulta', 'heikko', 'urhea', 'yritys', 
							'lahjakas', 'hymy', 'siirtomaa', 'puolella', 'pilata', 'takkuinen', 'simpukka', 'orpo', 'rahti', 'alibi', 
							'vastenmielinen', 'imeä', 'idea', 'petollinen', 'isä', 'hoito', 'legenda', 'aerodynaaminen', 'nuolla', 
							'seisoo', 'nainen', 'veneitä', 'saldo', 'polkupyöriä', 'syy', 'varpunen', 'haaste', 'aritmeettinen', 
							'sulkakynä', 'kaikuva', 'kosketus', 'luonnoton', 'romahdus', 'paholainen', 'inhimillisesti', 'tunnistaa', 
							'apulainen', 'galleria', 'samankaltaisia', 'mahtavasti', 'alaikäinen', 'velho', 'herkullinen', 'kukkainen', 
							'sitova', 'järjestelmän', 'mukaisesti', 'reitti', 'järkkymätön', 'asiakirja', 'hallusinaatio', 'omituinen', 
							'musta', 'lista', 'onnettomia', 'nekroottinen', 'tasoittaa', 'palaa', 'viehätys', 'lisätä', 'raha', 'parturi', 
							'hämmästyttävä', 'kova', 'parantaa', 'esittely', 'kemiallinen', 'pähkinäinen', 'tehoisku', 'vaivalloinen', 
							'paska', 'gaselli', 'jälkeen', 'kuningatar', 'käytännöllinen', 'lukea', 'kehto', 'viiltää', 'avata', 'tilanne', 
							'rohkea', 'voita', 'ansiokas', 'pirullinen', 'vuosikymmenen', 'ajan', 'kuvaa', 'eväste', 'kiistanalainen', 
							'tähtisumu', 'oikein', 'ripustaa', 'säätää', 'hiljaisuus', 'muukalainen', 'pirullinen', 'piilopaikka', 
							'tosiasia', 'toinen', 'kostea', 'rintareppu', 'kaari', 'esoteerinen', 'python', 'turkki', 'rehottavaa', 
							'kaulus', 'kypsä', 'tentti', 'näyte', 'röyhkeä', 'taivaallinen', 'tyyris', 'käsittelijä', 'etusijalle', 
							'hylkääminen', 'valittaa', 'lähetys', 'sytytin', 'hukkunut', 'salve', 'nälkäinen', 'lime', 'rakentaa', 
							'uudelleen', 'ääliö', 'huimapäinen', 'yksivärinen', 'tapahtumassa', 'oleva', 'lika', 'muualla', 'kuningaskunta', 
							'terveellistä', 'nainen', 'leikkaus', 'varovainen', 'sijainti', 'nuolla', 'epäilyttävä', 'vesikouru', 'heatset', 
							'kilpailla', 'antaa', 'valuutta', 'tahmea', 'kauneus', 'lyhty', 'hyvästi', 'ääni', 'kuollut', 'kasvot', 'alajoki', 
							'saarnata', 'unohtaa', 'myös', 'epäilemättä', 'kaaos', 'kätevyys', 'ego', 'gainsay', 'pirteä', 'runsaasti', 
							'sisältää', 'nahka', 'kalastaa', 'pelästyttää', 'versoa', 'hedelmällinen', 'kerma', 'rangaistus', "raa'asti", 
							'raskasydämisiä', 'solmu', 'kengät', 'pian', 'tarttuja', 'rikoksentekijä', 'ahdisti', 'vagabond', 'yksinäinen', 
							'syvyys', 'komento', 'rotu', 'miten', 'utuinen', 'tunsi', 'olonsa', 'mietiskelty', 'tunkkainen', 'havainnollistaa', 
							'aseet', 'unelmamaa', 'kuumempi', 'rikkaus', 'loinen', 'kappaleita', 'doberman', 'tarina', 'leipä', 'röyhkeä', 
							'näyttävät', 'epäsiisti', 'sammakko', 'baareja', 'kronologinen', 'liiallinen', 'hermostunut', 'raivoissaan', 
							'kurja', 'lihavoitu', 'tyhjyys', 'masentunut', 'toimeenpanija', 'veritahra', 'messias', 'päämaja', 'hapan', 
							'mökki', 'komea', 'olemassa', 'kaikesta', 'huolimatta', 'suhde', 'lahjakas', 'shamaani', 'syötti', 'kriittinen', 
							'avokado', 'tapa', 'kulkea', 'helmiä', 'vanhurskas', 'panssari', 'kirpeä', 'yhteys', 'shokki', 'maa', 
							'käsivarret', 'kommentti', 'tili', 'hankala', 'tarkoitus', 'värikynä', 'puhalluslamppu', 'pyöveli', 'epäuskoinen',
							'paino', 'rangaista', 'liha', 'hillitä', 'pölkkypää', 'valitettavaa', 'ovela', 'aallonmurtaja', 'lehmä', 'savi', 
							'hinta', 'hieno', 'tahraton', 'yleisö', 'kielletty', 'hullu', 'kerros', 'akku', 'materiaalia', 'värikäs', 'tusina', 
							'vastaa', 'tyyppi', 'kylä', 'kömpelö', 'tapauksessa', 'tietoisuus', 'oma', 'yhteydessä', 'vahingoittava', 'ennätys', 
							'tuhka', 'luukku', 'sammakkoeläin', 'pullo', 'tyyppi', 'saapumista', 'helmi', 'kompakti', 'huijari', 'kori', 
							'taitava', 'vaihtaa']